# Config for Mosaic H
septentrio_gnss_driver:
  ros__parameters:
    # device: tcp://192.168.3.1:28784
    serial: /dev/serial/by-id/usb-Septentrio_Septentrio_USB_Device_3815305-if02
    # baudrate: 921600
      # rx_serial_port: USB1 #TODO check ports
      # hw_flow_control: "off"

    stream_device:
      tcp:
        ip_server: ""
        port: 0        
      udp:
        ip_server: ""
        port: 0
        unicast_ip: ""

    configure_rx: true

    custom_commands_file: ""  

    osnma:
      mode: "off"
      ntp_server: ""
      keep_open: true

    frame_id: gnss

    imu_frame_id: imu

    poi_frame_id: base_link

    vsm_frame_id: vsm

    aux1_frame_id: aux1

    vehicle_frame_id: base_link

    local_frame_id: odom

    insert_local_frame: false

    get_spatial_config_from_tf: false

    lock_utm_zone: true

    use_ros_axis_orientation: true

    receiver_type: gnss    

    multi_antenna: true

    datum: Default

    poi_to_arp:
      delta_e: 0.0
      delta_n: 0.0
      delta_u: 0.0

    att_offset:
      heading: 0.0
      pitch: 0.0
      
    ant_type: "Unknown"
    ant_serial_nr: "Unknown"
    ant_aux1_type: "Unknown"
    ant_aux1_serial_nr: "Unknown"

    polling_period:
      pvt: 100
      rest: 500

    # time
    use_gnss_time: false
    ntp_server: true
    ptp_server_clock: false
    latency_compensation: true

    # RTK
    rtk_settings:  
      ntrip_1:
        id: ""
        caster: "rtk.sensorcloud.com"
        caster_port: 2101
        username: ""
        password: ""
        mountpoint: ""
        version: "v2"
        tls: false
        fingerprint: ""
        rtk_standard: "auto"
        send_gga: "auto" #TODO: try sec1
        keep_open: true

    publish:
      # For both GNSS and INS Rxs
      navsatfix: true
      gpsfix: true
      gpgga: true
      atteuler: true
      attcoveuler: true
      twist: true

    # logger

    activate_debug_log: false
